# Add mouse scroll
set -g mouse on
# tmux 2x theme start
# use a theme
#set -g @tmux2k-theme 'onedark'

# to show icons only
#set -g @tmux2k-icons-only true

# to customize duo bg and fg
# set -g @tmux2k-duo-fg "#1688f0" # this will get you duo blue shown above
# set -g @tmux2k-duo-bg "#000000" # this will set the bg for duo theme

# to set powerline symbols
#set -g @tmux2k-right-sep  # alternate right status bar sep
#set -g @tmux2k-window-list-right-sep  # alternate window list right sep

# to not show powerline
#set -g @tmux2k-show-powerline false

# set session icon, accepts: `session`, `window`, or any string
#set -g @tmux2k-session-icon " #S" # `#W` for window name
# tmux 2x theme ends

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tokyo night tmux plugin
set -g @plugin "janoamaral/tokyo-night-tmux"

# tmux2x plugin
#set -g @plugin '2kabhishek/tmux2k'

# tmux persistent state using resurrect and continuum 
set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'

#set -g @continuum-boot 'on'
#set -g @continuum-boot-options 'alacritty'
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
